<a href="https://colab.research.google.com/github/sylvia830/Real_Estate_Prices_Prediction/blob/main/Real_Estate_Prices_Polynomial_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
#import dataset
dataset = pd.read_csv('Real estate.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [9]:
dataset.head()

No  X1 transaction date  ...  X6 longitude  Y house price of unit area
0   1             2012.917  ...     121.54024                        37.9
1   2             2012.917  ...     121.53951                        42.2
2   3             2013.583  ...     121.54391                        47.3
3   4             2013.500  ...     121.54391                        54.8
4   5             2012.833  ...     121.54245                        43.1

[5 rows x 8 columns]

In [10]:
#give a brief summary of the dataset
dataset.info(null_counts=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Dtype  
---  ------                                  -----  
 0   No                                      int64  
 1   X1 transaction date                     float64
 2   X2 house age                            float64
 3   X3 distance to the nearest MRT station  float64
 4   X4 number of convenience stores         int64  
 5   X5 latitude                             float64
 6   X6 longitude                            float64
 7   Y house price of unit area              float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB


In [11]:
#split the dataset into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
#convert the scientific notation to float notation
float_formatter = "{:.7f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})
print(X_test)

**Using Polynomial Regression model to predict the prices:**

In [ ]:
#train the polynomial model on the training set 
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg =PolynomialFeatures(degree = 2)
x_poly = poly_reg.fit_transform(X)
lin_reg = LinearRegression()
lin_reg.fit(x_poly, y)

In [ ]:
#predict test results
y_pred = lin_reg.predict(poly_reg.fit_transform(X_test))
print(y_pred)

In [22]:
#compare predicted results with y_test
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)), 1))

[[27.1207998 27.3000000]
 [53.1538439 54.4000000]
 [24.6119159 22.0000000]
 [17.0330874 11.6000000]
 [52.5895601 45.4000000]
 [29.0575984 23.0000000]
 [21.4780263 21.8000000]
 [41.0042550 32.2000000]
 [38.7561982 37.4000000]
 [18.0985256 22.6000000]
 [16.1247055 17.4000000]
 [37.3618827 36.8000000]
 [26.9958306 23.1000000]
 [47.8470237 36.9000000]
 [52.7888830 56.3000000]
 [28.6425998 20.9000000]
 [52.6276389 43.5000000]
 [45.2389874 40.3000000]
 [19.4357772 27.7000000]
 [42.8510003 42.1000000]
 [47.7147180 46.6000000]
 [16.9257708 21.8000000]
 [39.6999584 38.1000000]
 [48.1703181 53.7000000]
 [48.2683124 57.1000000]
 [20.1465143 26.6000000]
 [25.0639003 32.1000000]
 [50.9950760 56.8000000]
 [53.5442502 43.1000000]
 [20.8971322 16.7000000]
 [28.1671803 33.4000000]
 [37.4313139 34.2000000]
 [41.5917966 39.6000000]
 [44.7437441 52.5000000]
 [45.5372004 47.1000000]
 [19.0300221 13.0000000]
 [38.1767658 37.5000000]
 [41.1678372 32.5000000]
 [46.6830337 42.3000000]
 [17.2217400 20.5000000]


In [23]:
#evaluate the model performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7934773157035822

In [ ]:
#train the polynomial regression model on the training set with a degree of 7
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg1 = PolynomialFeatures(degree=7)
x_poly1 = poly_reg1.fit_transform(X)
lin_reg1 = LinearRegression()
lin_reg1.fit(x_poly1, y)

In [ ]:
#predict the results for new degree
y_pred_new = lin_reg1.predict(poly_reg1.fit_transform(X_test))
print(y_pred_new)

In [26]:
#compare the new results with y_test
print(np.concatenate((y_pred_new.reshape(len(y_pred_new),1), y_test.reshape(len(y_test),1)),1))

[[27.1540587 27.3000000]
 [50.6734031 54.4000000]
 [21.9217161 22.0000000]
 [11.7490278 11.6000000]
 [45.1992048 45.4000000]
 [22.9252199 23.0000000]
 [22.4289966 21.8000000]
 [31.7919907 32.2000000]
 [37.5813999 37.4000000]
 [22.5755115 22.6000000]
 [17.4119020 17.4000000]
 [36.5633403 36.8000000]
 [22.5746324 23.1000000]
 [36.2847881 36.9000000]
 [55.4451674 56.3000000]
 [21.0229273 20.9000000]
 [44.2971183 43.5000000]
 [39.5938409 40.3000000]
 [27.7135448 27.7000000]
 [45.2512459 42.1000000]
 [46.4592821 46.6000000]
 [21.8444163 21.8000000]
 [38.0021282 38.1000000]
 [54.2703619 53.7000000]
 [59.5330206 57.1000000]
 [25.6980460 26.6000000]
 [32.1212427 32.1000000]
 [56.9357011 56.8000000]
 [43.0607804 43.1000000]
 [16.6337324 16.7000000]
 [33.7665376 33.4000000]
 [34.0424023 34.2000000]
 [40.3528064 39.6000000]
 [52.5376652 52.5000000]
 [47.6774408 47.1000000]
 [12.9750496 13.0000000]
 [37.2130298 37.5000000]
 [32.3375114 32.5000000]
 [44.9123353 42.3000000]
 [20.2617441 20.5000000]


In [27]:
#evalute the model performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_new)

0.9916092070641795

**Using Multiple Linear Regression model to predict prices**

In [ ]:
#train Multiple Linear Regression model on the training set 
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

In [ ]:
#predict test results
y_pred_lin = regressor.predict(X_test)
print(y_pred_lin)

In [28]:
#compare the predictions with y_test
print(np.concatenate((y_pred_lin.reshape(len(y_pred_lin),1), y_test.reshape(len(y_test),1)),1))

[[34.5922245 27.3000000]
 [47.5867348 54.4000000]
 [20.9226481 22.0000000]
 [12.4940283 11.6000000]
 [43.1188736 45.4000000]
 [34.5373971 23.0000000]
 [30.9452851 21.8000000]
 [45.3257759 32.2000000]
 [38.0483907 37.4000000]
 [13.9021720 22.6000000]
 [11.8979164 17.4000000]
 [38.5261129 36.8000000]
 [31.8806310 23.1000000]
 [45.3760469 36.9000000]
 [50.8465817 56.3000000]
 [36.2862735 20.9000000]
 [44.4107239 43.5000000]
 [45.2220300 40.3000000]
 [30.0527330 27.7000000]
 [43.7588833 42.1000000]
 [51.2945605 46.6000000]
 [28.4236779 21.8000000]
 [40.0221404 38.1000000]
 [46.8361249 53.7000000]
 [45.8497463 57.1000000]
 [27.9286420 26.6000000]
 [31.2219743 32.1000000]
 [47.7602854 56.8000000]
 [46.2885470 43.1000000]
 [15.0795206 16.7000000]
 [33.7556903 33.4000000]
 [34.8340303 34.2000000]
 [42.3205606 39.6000000]
 [44.6327856 52.5000000]
 [48.2258074 47.1000000]
 [12.9708751 13.0000000]
 [41.1958697 37.5000000]
 [41.2371303 32.5000000]
 [38.9984543 42.3000000]
 [13.3410848 20.5000000]


In [19]:
#evalute the model performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_lin)

0.7061990777414744